### PR TITLE
Couple usability / compatibility tweaks

### PR DESCRIPTION
**Pull request by vit-zikmund**
Hi @agarciadom,
Once I started to poke in the script in #122, I saw it could use some further polishing of things that bit me during getting acquainted. Here's a triplet of changes I locally tested to work and personally believe make the usability of the script a tiny bit better:
- v4l2loopback device detection - the v4l2loopback driver has a native sysfs way of tracking which devices it manages, so one shouldn't need the `v4l2-ctl` utility - which was originally missing for me and I had to install it just for this (and then for debugging, I admit :smile:).
- i saw you had problems with the image flipping, there's a silly fix that does the trick for me
- I also kinda disliked the script's default resolution, which I find too small for today's videoconference standards Also it makes more sense to me for the use to set this in the IPWebcam app (to plan the phone-to-pc network load accordingly). I had no issues with strange dimensions being used as described in #97, so I made the dimensions overrides entirely voluntary and generally inferred from the source.

This would need some further testing on some other distros than my bleeding edge fedora 37 :slightly_smiling_face: , but I hope it's worth it.

### CODE REVIEW

**Comment by vit-zikmund** [comment]
Just added a couple parameters for video cropping.

**Comment by vit-zikmund** [comment]
Here's a commit that beefs up the background gst stream handling:
- won't run while stream is dead, will err and cleanup instead
- apart from the usual enter to terminate it handles SIGINT and SIGTERM for that purpose

(This little tool along with the IP Webcam saved me quite some money for a higher-end webcam, especially by showing me the way, so I hope it's not bothersome if I send back a couple useful improvements.)

**Comment by vit-zikmund** [comment]
Hello @agarciadom, I understand this project might become marginal for you, but please let me know if the PR (and any further ones) are appreciated.
I tried my best to make all the commits in the PR branch rather well defined so you would be able to review, but I'd love to build more on top of those changes, but I know each further change decreases the likelihood of them getting ever reviewed (It seems I crossed that threshold, anyway :expressionless:). I could naturally carry on in my fork not caring about upstreaming any improvements, but that (still) seems like a waste. I know the author of IP Webcam has not released any update since 2021, but it's obviously still popular given its 60k downloads last month. The project is the only known OSS alternative even referenced from the IP Webcam software itself. I don't think it's yet the time to let it die :slightly_smiling_face: Please, LMK if there's something I can do to help you out.

**Comment by agarciadom** [comment]
Hi @vit-zikmund! Your contributions are definitely appreciated, it's just that I haven't had much time away from my day job to look after the PRs in this project, and I don't use it anymore on a daily basis. I'll give this a look :-).

**Comment by agarciadom** [comment]
This is really nice! There are some Bash tricks here which I wasn't familiar with :-). I'm glad that someone finally tackled the capture of the SIGINT and SIGTERM signals the proper way. Thank you for your contribution!

**Comment by vit-zikmund** [comment]
Thank you for taking the time for the review! ;)

**Pull request merged**
